import geb.Browser
import groovyx.net.http.HTTPBuilder
import org.apache.http.HttpResponse

import static groovyx.net.http.ContentType.URLENC

/**
 * Created by vinicius on 08/01/17.
 */
class CrawlerTest {



    static void main(String... args) {
        def start = System.currentTimeMillis()
        for (locA in locations) {
            for (locB in locations) {
                if (locA != locB) {
                    searchLines(locA, locB);
                }
            }
        }
        println "Total time: ${(System.currentTimeMillis()-start)/1000.0}"
    }

    static def searchLines(String from, String to) {
        def http = new HTTPBuilder('https://www.portalpassagens.com.br')
        http.ignoreSSLIssues()
        def postBody = [origem:from, destino:to, dataInicial:'25/01/2017',
                dataFinal:'', idioma:'pt', 'submit.x':54, 'submit.y':26];
        http.post(path:'/VendaWeb/busca', body: postBody,
                requestContentType: URLENC ) { postResp ->
            def http2 = new HTTPBuilder('https://www.portalpassagens.com.br')
            http2.ignoreSSLIssues()
            http2.get([path:'/VendaWeb/consulta']) { HttpResponse resp ->
                resp.entity.writeTo(System.out);

            }
        }
    }

    static String[] locations = [
        "SAO PAULO (SP)",
        "JUNDIAI (SP)",
        "CAMPINAS (SP)",
        "AMERICANA (SP)",
        "MOGI GUACU (SP)",
        "MOGI MIRIM (SP)",
        "ITAPIRA (SP)",
        "ELEUTERIO (SP)",
        "DIVISA (MG)",
        "BARAO A.NOGUEIRA (SP)",
        "JACUTINGA (MG)",
        "CANELEIRAS (MG)",
        "OURO FINO (MG)",
        "INCONFIDENTE (MG)",
        "FAZENDA AGENOR (MG)",
        "BORDA DA MATA (MG)",
        "DRAUZIO (MG)",
        "POUSO ALEGRE (MG)",
        "SERTAOZINHO (MG)",
        "PONTE PRETA (MG)",
        "FAZENDA PAULINIA (MG)",
        "MOCOCA (MG)",
        "MONTE SIAO (MG)",
        "PINHALZINHO GOIS (MG)",
        "IGREJA FURNAS (MG)",
        "ALTO SERRA (MG)",
        "BOA VENTURA (MG)",
        "BUENO BRANDAO (MG)",
        "ALTO MATA (MG)",
        "OLEGARIO MACIEL (MG)",
        "RIO PEDRAS (MG)",
        "BRASILINHA (MG)",
        "PORTO SAPUCAI (MG)",
        "SANTA RITA SAPUCAI (MG)",
        "RETIRO (MG)",
        "ENTRADA OLEGARIO MACIEL (MG)",
        "PIRANGUINHO (MG)",
        "ITAJUBA (MG)",
        "CANTA GALO (MG)",
        "ENTRADA S.J.BENTO (MG)",
            /*
        "TRES BARRAS (MG)",
        "IPUIUNA (MG)",
        "SAN.R.CALDAS (MG)",
        "BARBOSAS (MG)",
        "HORT.FLOREST (MG)",
        "CALDAS (MG)",
        "PONTE BERALD (MG)",
        "LARANJEIRAS (MG)",
        "POCOS DE CALDAS (MG)",
        "POCINHOS (MG)",
        "ESCOLA PAULINA (MG)",
        "IBITIURA DEMINAS (MG)",
        "FAZENDA SANTA MARIA (MG)",
        "FAZENDA DA PRATA (MG)",
        "ANDRADAS (MG)",
        "CAREACU (MG)",
        "SAO GONCALO DO SAPUCA (MG)",
        "CAMPANHA (MG)",
        "CAMBUQUIRA (MG)",
        "BR 267/383 (MG)",
        "CAXAMBU (MG)",
        "SAO LOURENCO (MG)",
        "SAO JOSE ALEGRE (MG)",
        "PEDRALVA (MG)",
        "CRISTINA (MG)",
        "CARMO MINAS (MG)",
        "ENTRADA LAMBARI (MG)",
        "ENTRADA CONCEICAO RIO VERDE (MG)",
        "ESCOLA (MG)",
        "ALBERTAO (MG)",
        "CACHOEIRA DE MINAS (MG)",
        "CONCEICAO DOS OUROS (MG)",
        "PARAISOPOLIS (MG)",
        "CACHOEIRINHA (MG)",
        "HELIODORA (MG)",
        "SAO SEBASTIAO BELA VISTA (MG)",
        "PENHA (MG)",
        "ATIRADO (MG)",
        "NATERCIA (MG)",
        "ENTRADA ITAIM (MG)",
        "COSTINHA (MG)",
        "FURNAS (MG)",
        "POSTO ALIANCA (MG)",
        "ENTRADA HELIODORA (MG)",
        "HELIODORA (MG)",
        "SAO SEBASTIAO BELA VISTA (MG)",
        "PENHA (MG)",
        "ATIRADO (MG)",
        "NATERCIA (MG)",
        "BELO HORIZONTE (MG)",
        "ENTRADA ITAGUARA (MG)",
        "ENTRADA CARMO DE MINAS (MG)",
        "ENTRADA OLIVEIRA (MG)",
        "ENTRADA SANTO ANTONIO AMPARO (MG)",
        "ENTRADA PERDOES (MG)",
        "ENTRADA LAVRAS (MG)",
        "ENTRADA CARMO DA CACHOEIRA (MG)",
        "ENTRADA TRES CORACOES (MG)",
        "ENTRADA SAO GONCALO SAPUCAI (MG)",
        "VILA PASSA QUATRO (MG)",
        "BAIRRO AFONSOS (MG)",
        "ALTO SERRA (MG)",
        "ESPIRITO SANTO.DOURADO (MG)",
        "SENADOR JOSE BENTO (MG)",
        "AGUA PARADA (MG)",
        "MACHADO (MG)",
        "CARVALHOPOLI (MG)",
        "DOURADINHO (MG)",
        "CORDISLANDIA (MG)",
        "AGUA COMPRIDA (MG)",
        "TURVOLANDIA (MG)",
        "ENTRADA CORDISLANDIA (MG)",
        "RIO DOURADO (MG)",
        "ENTRADA ELOI MENDES (MG)",
        "ENTRADA PARAGUACU (MG)",
        "TRES CORACOES (MG)",
        "CARMO DA CACHOEIRA (MG)",
        "COQUEIRAL (MG)",
        "POUSO ALTO (MG)",
        "SANTANA CAPIVARI (MG)",
        "ITANHANDU (MG)",
        "BAEPENDI (MG)",
        "VARGINHA (MG)",
        "ELOI MENDES (MG)",
        "PARAGUACU (MG)",
        "ALFENAS (MG)",
        "NEPOMUCENO (MG)",
        "ENTRADA COQUEIRAL (MG)",
        "SANTANA DA VARGEM (MG)",
        "BOA ESPERANCA (MG)",
        "CAMPOS GERAIS (MG)",
        "CAMPESTRE (MG)",
        "ENTRADA BANDEIRA (MG)",
        "ENTRADA CAMPESTRE (MG)",
        "CONCEICAO DO RIO VERDE (MG)",
        "LAMBARI (MG)",
        "JESUANIA (MG)",
        "TRES PONTAS (MG)",
        "CRUZILIA (MG)",
        "FAZENDA SAPE (MG)",
        "DESCAROCADOR (MG)",
        "PONTE AMORAS (MG)",
        "GASPAR LOPES (MG)",
        "CORREGO DO OURO (MG)",
        "DIST.C.OURO (MG)",
        "PASSA QUATRO (MG)",
        "ENTRADA CAMPANHA (MG)",
        "LIMEIRA (SP)",
        "NOVA ODESSA (MG)",
        "SEG PATRIMO (MG)",
        "BORESCA (MG)",
        "LAVRAS (MG)",
        "RIO CLARO (MG)",
        "BAIRRO CARNEIRO (MG)",
        "SANTA QUITERIA (MG)",
        "SAO JOAO (MG)",
        "APARECIDA (SP)",
        "BARBACENA (MG)",
        "BARROSO (MG)",
        "SÃO JOAO DEL REI (MG)",
        "NAZARENO (MG)",
        "ITUTINGA (MG)",
        "ITUMIRIM (MG)",
        "MADRE DEUS MINAS (MG)",
        "LORENA (SP)",
        "GUARATINGUETA (SP)",
        "TAUBATE (SP)",
        "SAO JOSE DOS CAMPOS (SP)",
        "MARCO DIVISORIO (MG)",
        "CAMANDUCAIA (MG)",
        "ITATIBA (SP)",
        "ENTRADA EXTREMA (MG)",
        "ENTRADA JUATUBA (MG)",
        "ENTRADA MATEUS LEME (MG)",
        "ENTRADA ITAUNA (MG)",
        "ENTRADA DIVINOPOLIS. (MG)",
        "ENTRADA ITAPICIRICA (MG)",
        "FORMIGA (MG)",
        "ENTRADA PIMENTA (MG)",
        "PIUMHI (MG)",
        "CAPITOLIO (MG)",
        "PASSOS (MG)",
        "BR354 MG050 (MG)",
        "PAINS (MG)",
        "ENTRADA FORMIGA (MG)",
        "ITAU DE MINAS (MG)",
        "PRATAPOLIS (MG)",
        "CASSIA (MG)",
        "ALPINOPOLIS (MG)",
        "CARMO RIO CLARO (MG)",
        "ENTRADA CONCEICAO APARECIDA (MG)",
        "ALTEROSA (MG)",
        "AREADO (MG)",
        "MONTE BELO (MG)",
        "MUZAMBINHO (MG)",
        "GUAXUPE (MG)",
        "DIVINOPOLIS (MG)",
        "MORRO FERRO (MG)",
        "SAO SEBASTIAO DO PARAISO (MG)",
        "ENTRADA CAPITOLIO (MG)",
        "ENTRADA BETIM (MG)",
        "ENTRADA IGARAPE (MG)",
        "PONTE VELOSO (MG)",
        "ENTRADA SANTA TEREZINHA (MG)",
        "CARVALHOS (MG)",
        "ENTRADA ITAGUARA (MG)",
        "PONTE PARA (MG)",
        "BRASILANDIA (MG)",
        "ENTRADA OLIVEIRA (MG)",
        "SANTO ANTONIO AMPARO (MG)",
        "BOM SUCESSO (MG)",
        "RIBEIRAO PRETO (SP)",
        "PORTE FERREIRA (SP)",
        "PIRASSUNUNGA (SP)",
        "CASCALHO (SP)",
        "POSTO MOGI GUACU (SP)",
        "SAPUCAI (MG)",
        "ENTRADA CORREGO FUNDO (MG)",
        "SAO TOME LETRAS. (MG)",
        "AURELIO (MG)",
        "ESPRAIADO (MG)",
        "PARQUE INDUSTRIAL (MG)",
        "PALMELA (MG)",
        "RIBEIRAO VERMELHO (MG)",
        "S.MONJOLINHO (MG)",
        "FAZ PE.NEGRA (MG)",
        "ENTRADA CAREACU (MG)",
        "RIBEIRO (MG)",
        "BARRA GRANDE (MG)",
        "SAO DOMINGOS (MG)",
        "PAULINO PAIX (MG)",
        "ENTRADA SANTA BARBARA (MG)",
        "BAIRRO LAMBARI (MG)",
        "MARIA FE (MG)",
        "ANO BOM (MG)",
        "PIMENTA (MG)",
        "PINDAMONHANG (SP)",
        "ROSEIRA (SP)",
        "DELFIM MOREIRA (MG)",
        "SANTO ANTONIO DO PINHAL (SP)",
        "SAO BENTO DO SAPUCAI (SP)",
        "SAPUCAI MIRI (MG)",
        "BRASOPOLIS (MG)",
        "ENTRADA NAZARENO (MG)",
        "CALDAS (MG)",
        "BARAO NOGUEIRA (SP)",
        "E.OLI.CURRAL (MG)",
        "ENTRADA PERDOES GRAAL (MG)",
        "AGUA LIMPA (MG)",
        "BARREIRO (MG)",
        "DIAS (MG)",
        "CRUZ VERA (MG)",
        "GONCALVES (MG)",
        "BRUMADO (MG)",
        "CUBATAO (MG)",
        "MARMELOPOLIS (MG)",
        "BAIRRO ILHA (MG)",
        "PEDRAO (MG)",
        "PE SERRA (MG)",
        "GERIVA (MG)",
        "PTE.ZINCO (MG)",
        "WENC. BRAZ (MG)",
        "SAO PEDRO (MG)",
        "CAMPOS (MG)",
        "SERRINHA (MG)",
        "DOM VICOSO (MG)",
        "S.JOAO (MG)",
        "ENTRADA LAVRAS (MG)",
        "ENTRADA TRES CORACOES (MG)",
        "ALTO D.SERRA (MG)",
        "ITUMIRIM (MG)",
        "RIO PRETO (SP)",
        "LEFREVE (SP)",
        "PIRACUAMA (SP)",
        "ITUMIRIM MG2 (MG)",
        "CORREGO FUNDO (MG)",
        "FRANCA (SP)",
        "CAPETINGA (MG)",
        "ITIRAPUA (SP)",
        "PATROCINIO P (SP)",
        "BATATAIS (SP)",
        "MG344/444 (MG)",
        "MG444/346 (SP)",
        "ENTRADA PATROCINIO PAULISTA (SP)",
        "RESTAU.TILAU (SP)",
        "ENTRADA FRANCA (SP)",
        "ENTRADA BATATAIS (SP)",
        "ENTRADA RIBEIRAO PRETO (SP)",
        "ENTRADA PASSOS (MG)",
        "ENTRADA ITAU (MG)",
        "RODOSHO.ITAU (MG)",
        "ENTRADA IBIRACI (MG)",
        "IBIRACI (MG)",
        "MG/SP 438 (MG)",
        "CASA SECA (SP)",
        "ENTRADA MUNIC (SP)",
        "DELFINOPOLIS (MG)",
        "FAZENDA ITATUBA (MG)",
        "DUAS VENDAS (MG)",
        "ENTRADA CARMO DE MINAS (MG)",
        "SANTA CRUZ DA PRATA (MG)",
        "BIGUATINGA (MG)",
        "JACUI (MG)",
        "B.JESUSPENHA (MG)",
        "S.PEDRO UNIA (MG)",
        "ZE ANGELO (MG)",
        "IGREJINHA (MG)",
        "MUMBUQUINHA (MG)",
        "NOVA REZENDE (MG)",
        "PTE-SERRA (MG)",
        "PTE-NOVA (MG)",
        "JURUAIA (MG)",
        "ENTRADA JURUAIA (MG)",
        "GUINE (MG)",
        "MATA SINO (MG)",
        "CORREGO CAVA (MG)",
        "CEDRO (MG)",
        "CONC.APARECI (MG)",
        "PENHA (MG)",
        "PETUNIA (MG)",
        "FAZENDA PAULISTA (MG)",
        "CONGONHAL (MG)",
        "TREMEMBE (SP)",
        "MG050/MG446 (MG)",
        "BR265/MG184 (MG)",
        "PTE.SAPUCAI (MG)",
        "LAGOINHA/BR (MG)",
        "BARREIRO (MG)",
        "ILICINEA (MG)",
        "AGUAS VERDES (MG)",
        "CORREGO CAMPO (MG)",
        "FAZENDA CAXAMBU (MG)",
        "SETE CACHOEIRA (MG)",
        "BR265/BR369 (MG)",
        "VIADUTO (MG)",
        "BR381/MG167 (MG)",
        "FLORA (MG)",
        "GUAPE (MG)",
        "PAINEIRAS (MG)",
        "CACHOEIRA (MG)",
        "MUNDO NOVO (MG)",
        "ESMERIL (MG)",
        "MON.S PAULO (MG)",
        "SERVO (MG)",
        "PALMELA (MG)",
        "ZE DE (MG)",
        "ESCOLA (MG)",
        "FAZ CAXAMBU (MG)",
        "FAZ IPIRANGA (MG)",
        "ENTRADA CAMBUQUI (MG)",
        "BRAGANCA PAULISTA (SP)",
        "TOLEDO (MG)",
        "ESTIVA AGUDO (SP)",
        "PON.LEME (SP)",
        "J.GOMES (SP)",
        "JOSE LEME (SP)",
        "DIV MG146 (MG)",
        "SQUILACE (SP)",
        "PEDRA BELA (SP)",
        "MUNHOZ (MG)",
        "B.PEREIRAS (MG)",
        "SAO BRAS (MG)",
        "PINHALZINHO (SP)",
        "SOCORRO (SP)",
        "EXTREMA (MG)",
        "CAMPO DO MEIO (MG)"
        */
    ];
}
